# Generated by Django 5.2.8 on 2025-11-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conversa',
                'verbose_name_plural': 'Conversas',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text='Prompt usado para gerar a imagem', verbose_name='Prompt')),
                ('image_url', models.URLField(help_text='URL da imagem gerada pelo DALL·E', max_length=2000, verbose_name='URL da Imagem')),
                ('revised_prompt', models.TextField(blank=True, help_text='Prompt revisado pelo DALL·E', verbose_name='Prompt Revisado')),
                ('model', models.CharField(default='dall-e-3', max_length=50, verbose_name='Modelo')),
                ('size', models.CharField(default='1024x1024', max_length=20, verbose_name='Tamanho')),
                ('quality', models.CharField(default='standard', max_length=20, verbose_name='Qualidade')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Imagem Gerada',
                'verbose_name_plural': 'Imagens Geradas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LLMUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, help_text='Pergunta feita pelo usuário', null=True, verbose_name='Pergunta')),
                ('provider', models.CharField(help_text='Ex: openai, anthropic, google', max_length=50, verbose_name='Provedor')),
                ('model_name', models.CharField(help_text='Ex: gpt-4o, claude-3-5-sonnet-20241022', max_length=100, verbose_name='Modelo')),
                ('input_tokens', models.IntegerField(default=0, help_text='Tokens enviados (prompt + contexto)', verbose_name='Tokens de Entrada')),
                ('output_tokens', models.IntegerField(default=0, help_text='Tokens gerados na resposta', verbose_name='Tokens de Saída')),
                ('total_tokens', models.IntegerField(default=0, help_text='Soma de entrada + saída', verbose_name='Total de Tokens')),
                ('cache_creation_tokens', models.IntegerField(default=0, help_text='Tokens usados para criar o cache (Anthropic)', verbose_name='Tokens de Criação de Cache')),
                ('cache_read_tokens', models.IntegerField(default=0, help_text='Tokens lidos do cache (Anthropic - ~90% desconto)', verbose_name='Tokens Lidos do Cache')),
                ('input_cost', models.DecimalField(decimal_places=6, default=0, help_text='Custo estimado dos tokens de entrada', max_digits=10, verbose_name='Custo de Entrada (USD)')),
                ('output_cost', models.DecimalField(decimal_places=6, default=0, help_text='Custo estimado dos tokens de saída', max_digits=10, verbose_name='Custo de Saída (USD)')),
                ('cache_creation_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Custo de Criação de Cache (USD)')),
                ('cache_read_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Custo de Leitura de Cache (USD)')),
                ('total_cost', models.DecimalField(decimal_places=6, default=0, help_text='Soma de todos os custos', max_digits=10, verbose_name='Custo Total (USD)')),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Tempo em milissegundos da chamada', null=True, verbose_name='Tempo de Resposta (ms)')),
                ('context_size', models.IntegerField(default=0, help_text='Número de caracteres do contexto adicional carregado', verbose_name='Tamanho do Contexto')),
                ('tools_used', models.JSONField(blank=True, default=list, help_text='Lista de ferramentas chamadas nesta interação', verbose_name='Ferramentas Usadas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Uso de LLM',
                'verbose_name_plural': 'Usos de LLM',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuário'), ('assistant', 'Assistente'), ('system', 'Sistema')], max_length=10, verbose_name='Papel')),
                ('content', models.TextField(help_text='Conteúdo da mensagem em texto', verbose_name='Conteúdo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['created_at'],
            },
        ),
    ]
