# Generated by Django 5.2.8 on 2025-11-26 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neo_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to='agents.conversation', verbose_name='Conversa'),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agents.conversation', verbose_name='Conversa'),
        ),
        migrations.AddField(
            model_name='llmusage',
            name='message',
            field=models.ForeignKey(blank=True, help_text='Mensagem associada a este uso de LLM', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_usages', to='agents.message', verbose_name='Mensagem'),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to='agents.message', verbose_name='Mensagem'),
        ),
        migrations.AddIndex(
            model_name='llmusage',
            index=models.Index(fields=['-created_at'], name='agents_llmu_created_a04123_idx'),
        ),
        migrations.AddIndex(
            model_name='llmusage',
            index=models.Index(fields=['provider', 'model_name'], name='agents_llmu_provide_31ae02_idx'),
        ),
    ]
