# Generated by Django 5.2.8 on 2025-11-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='Resposta da IA'),
        ),
    ]
