# Generated by Django 5.2.8 on 2025-12-16 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_message_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, help_text='Mensagem à qual esta mensagem está respondendo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='agents.message', verbose_name='Resposta a'),
        ),
    ]
