# Generated by Django 5.2.8 on 2025-12-18 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_message_reply_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/%d/', verbose_name='Arquivo')),
                ('attachment_type', models.CharField(choices=[('image', 'Imagem'), ('file', 'Arquivo'), ('audio', 'Áudio'), ('video', 'Vídeo')], max_length=10, verbose_name='Tipo')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nome do arquivo')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME type')),
                ('size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamanho (bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='agents.message', verbose_name='Mensagem')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
                'ordering': ['created_at'],
            },
        ),
    ]
